/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  IsEnum,
  IsOptional,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumVariantMaterial } from "./EnumVariantMaterial";
import { EnumVariantOption } from "./EnumVariantOption";
import { Product } from "../../product/base/Product";
import { EnumVariantSize } from "./EnumVariantSize";
@ObjectType()
class Variant {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    enum: EnumVariantMaterial,
  })
  @IsEnum(EnumVariantMaterial)
  @IsOptional()
  @Field(() => EnumVariantMaterial, {
    nullable: true,
  })
  material?: "basic" | "wooden" | null;

  @ApiProperty({
    required: false,
    enum: EnumVariantOption,
  })
  @IsEnum(EnumVariantOption)
  @IsOptional()
  @Field(() => EnumVariantOption, {
    nullable: true,
  })
  option?: "size" | "material" | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Field(() => Number)
  price!: number;

  @ApiProperty({
    required: false,
    type: () => Product,
  })
  @ValidateNested()
  @Type(() => Product)
  @IsOptional()
  product?: Product | null;

  @ApiProperty({
    required: false,
    enum: EnumVariantSize,
  })
  @IsEnum(EnumVariantSize)
  @IsOptional()
  @Field(() => EnumVariantSize, {
    nullable: true,
  })
  size?: "S70x50" | "S50x40" | "S40x30" | "S30x21" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  sku!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { Variant };
