/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumVariantMaterial } from "./EnumVariantMaterial";
import {
  IsEnum,
  IsOptional,
  IsNumber,
  ValidateNested,
  IsString,
} from "class-validator";
import { EnumVariantOption } from "./EnumVariantOption";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { Type } from "class-transformer";
import { EnumVariantSize } from "./EnumVariantSize";
@InputType()
class VariantUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumVariantMaterial,
  })
  @IsEnum(EnumVariantMaterial)
  @IsOptional()
  @Field(() => EnumVariantMaterial, {
    nullable: true,
  })
  material?: "basic" | "wooden" | null;

  @ApiProperty({
    required: false,
    enum: EnumVariantOption,
  })
  @IsEnum(EnumVariantOption)
  @IsOptional()
  @Field(() => EnumVariantOption, {
    nullable: true,
  })
  option?: "size" | "material" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumVariantSize,
  })
  @IsEnum(EnumVariantSize)
  @IsOptional()
  @Field(() => EnumVariantSize, {
    nullable: true,
  })
  size?: "S70x50" | "S50x40" | "S40x30" | "S30x21" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  sku?: string;
}
export { VariantUpdateInput };
