/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ArtistCreateNestedManyWithoutTagsInput } from "./ArtistCreateNestedManyWithoutTagsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CollectionCreateNestedManyWithoutTagsInput } from "./CollectionCreateNestedManyWithoutTagsInput";
import { ProductCreateNestedManyWithoutTagsInput } from "./ProductCreateNestedManyWithoutTagsInput";
@InputType()
class TagCreateInput {
  @ApiProperty({
    required: false,
    type: () => ArtistCreateNestedManyWithoutTagsInput,
  })
  @ValidateNested()
  @Type(() => ArtistCreateNestedManyWithoutTagsInput)
  @IsOptional()
  @Field(() => ArtistCreateNestedManyWithoutTagsInput, {
    nullable: true,
  })
  artists?: ArtistCreateNestedManyWithoutTagsInput;

  @ApiProperty({
    required: false,
    type: () => CollectionCreateNestedManyWithoutTagsInput,
  })
  @ValidateNested()
  @Type(() => CollectionCreateNestedManyWithoutTagsInput)
  @IsOptional()
  @Field(() => CollectionCreateNestedManyWithoutTagsInput, {
    nullable: true,
  })
  collections?: CollectionCreateNestedManyWithoutTagsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  handle?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metaDescription?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metaTitle?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductCreateNestedManyWithoutTagsInput,
  })
  @ValidateNested()
  @Type(() => ProductCreateNestedManyWithoutTagsInput)
  @IsOptional()
  @Field(() => ProductCreateNestedManyWithoutTagsInput, {
    nullable: true,
  })
  products?: ProductCreateNestedManyWithoutTagsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { TagCreateInput };
