/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ArtistUpdateManyWithoutTagsInput } from "./ArtistUpdateManyWithoutTagsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CollectionUpdateManyWithoutTagsInput } from "./CollectionUpdateManyWithoutTagsInput";
import { ProductUpdateManyWithoutTagsInput } from "./ProductUpdateManyWithoutTagsInput";
@InputType()
class TagUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ArtistUpdateManyWithoutTagsInput,
  })
  @ValidateNested()
  @Type(() => ArtistUpdateManyWithoutTagsInput)
  @IsOptional()
  @Field(() => ArtistUpdateManyWithoutTagsInput, {
    nullable: true,
  })
  artists?: ArtistUpdateManyWithoutTagsInput;

  @ApiProperty({
    required: false,
    type: () => CollectionUpdateManyWithoutTagsInput,
  })
  @ValidateNested()
  @Type(() => CollectionUpdateManyWithoutTagsInput)
  @IsOptional()
  @Field(() => CollectionUpdateManyWithoutTagsInput, {
    nullable: true,
  })
  collections?: CollectionUpdateManyWithoutTagsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  handle?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metaDescription?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metaTitle?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductUpdateManyWithoutTagsInput,
  })
  @ValidateNested()
  @Type(() => ProductUpdateManyWithoutTagsInput)
  @IsOptional()
  @Field(() => ProductUpdateManyWithoutTagsInput, {
    nullable: true,
  })
  products?: ProductUpdateManyWithoutTagsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;
}
export { TagUpdateInput };
