/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSON, IsOptional, IsString, ValidateNested } from "class-validator";
import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ProductCreateNestedManyWithoutArtistsInput } from "./ProductCreateNestedManyWithoutArtistsInput";
import { Type } from "class-transformer";
import { TagCreateNestedManyWithoutArtistsInput } from "./TagCreateNestedManyWithoutArtistsInput";
@InputType()
class ArtistCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  data?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  handle?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metaDescription?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metaTitle?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProductCreateNestedManyWithoutArtistsInput,
  })
  @ValidateNested()
  @Type(() => ProductCreateNestedManyWithoutArtistsInput)
  @IsOptional()
  @Field(() => ProductCreateNestedManyWithoutArtistsInput, {
    nullable: true,
  })
  products?: ProductCreateNestedManyWithoutArtistsInput;

  @ApiProperty({
    required: false,
    type: () => TagCreateNestedManyWithoutArtistsInput,
  })
  @ValidateNested()
  @Type(() => TagCreateNestedManyWithoutArtistsInput)
  @IsOptional()
  @Field(() => TagCreateNestedManyWithoutArtistsInput, {
    nullable: true,
  })
  tag?: TagCreateNestedManyWithoutArtistsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  translations?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  wikidata?: string | null;
}
export { ArtistCreateInput };
